### ISSUE TITLE
有的帖子下不全

### ISSUE THREAD

**Issue by weigeloveu** [yikesoftware/t66y_spider#1]
如花子的帖子标着30p，下载下来只有20几p。
还有是否可加一个选项只趴达盖尔

**Comment by yikesoftware** [comment]
嗯的确有这个问题，可能是多线程没弄好，找时间改一下。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"weigeloveu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月21日(星期二) 上午10:42
收件人:&nbsp;"yikesoftware/t66y_spider"<t66y_spider@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yikesoftware/t66y_spider] 有的帖子下不全 (#1)




如花子的帖子标着30p，下载下来只有20几p。
 还有是否可加一个选项只趴达盖尔

**Comment by weigeloveu** [comment]
多谢大佬开发今天试了新版本，有的还是下不全。
`download: http://www.xoimg.club/u/20200125/2154385.jpg( 5 / 17 )
download: https://www.privacypic.com/images/2020/01/06/DCA810B3CAF2E3FA55291CD4629AB606a4b231cb455a3a3c.jpgconnect failed: HTTPConnectionPool(host='localhost', port=10888): Max retries exceeded with url: http://www.xoimg.club/u/20200125/2154385.jpg (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027BCD18F8E0>: Failed to establish a new connection: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。')))
connect failed: HTTPSConnectionPool(host='www.privacypic.com', port=443): Max retries exceeded with url: /images/2020/01/06/DCA810B3CAF2E3FA55291CD4629AB606a4b231cb455a3a3c.jpg (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Privoxy Error')))
下载已完成！`
还有个问题是不用代理的话要用啥指令

**Comment by yikesoftware** [comment]
hhh，我以为大家都要代理就没设关闭
关于帖子下不全我有手动研究过，有的时候是因为一些图床有限制，并发下载太多会断掉



---原始邮件---
发件人: "weigeloveu"<notifications@github.com&gt;
发送时间: 2020年1月31日(周五) 晚上7:04
收件人: "yikesoftware/t66y_spider"<t66y_spider@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"赤道企鹅"<1532494123@qq.com&gt;;
主题: Re: [yikesoftware/t66y_spider] 有的帖子下不全 (#1)



多谢大佬开发今天试了新版本，有的还是下不全。
 download: http://www.xoimg.club/u/20200125/2154385.jpg( 5 / 17 ) download: https://www.privacypic.com/images/2020/01/06/DCA810B3CAF2E3FA55291CD4629AB606a4b231cb455a3a3c.jpgconnect failed: HTTPConnectionPool(host='localhost', port=10888): Max retries exceeded with url: http://www.xoimg.club/u/20200125/2154385.jpg (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027BCD18F8E0&gt;: Failed to establish a new connection: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。'))) connect failed: HTTPSConnectionPool(host='www.privacypic.com', port=443): Max retries exceeded with url: /images/2020/01/06/DCA810B3CAF2E3FA55291CD4629AB606a4b231cb455a3a3c.jpg (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Privoxy Error'))) 下载已完成！
 还有个问题是不用代理的话要用啥指令

**Comment by yikesoftware** [comment]
刚刚改了下，发现似乎是代理的问题，部分HTTPS的图床链接会报错，目前还没啥办法，但是大部分是没问题的。新增了一个关闭代理的参数 ```[-p 0]```。

**Comment by weigeloveu** [comment]
感谢大佬修改，无奈小白不动代码不能分忧，刚才试了一下-p参数好像不好使
`[w@localhost t66y_spider]$ python Spider_of_t66y.py -c 2 -p 0
{'http': 'http://localhost:1080', 'https': 'https://localhost:1080'}
path[',/t66y'] exists
Enjoy your life!
将下载【達蓋爾的旗幟】的图片...
开始下载第 1 页
path['./t66y/達蓋爾的旗幟'] exists
Connect failed: HTTPConnectionPool(host='localhost', port=1080): Max retries exceeded with url: http://t66y.com/thread0806.php?fid=16&search=&page=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff0ea644750>: Failed to establish a new connection: [Errno 111] Connection refused')))
[w@localhost t66y_spider]$ 

`

**Comment by weigeloveu** [comment]
刚才试着改成了useProxy=False，好用了。多谢大佬了 我再看看爬的全不全

**Comment by yikesoftware** [comment]
不好意思，漏了个东西，加上了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"weigeloveu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月31日(星期五) 晚上10:50
收件人:&nbsp;"yikesoftware/t66y_spider"<t66y_spider@noreply.github.com&gt;;
抄送:&nbsp;"赤道企鹅"<1532494123@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yikesoftware/t66y_spider] 有的帖子下不全 (#1)




刚才试着改成了useProxy=False，好用了。多谢大佬了 我再看看爬的全不全

**Comment by weapon14** [comment]
因为没有代理，意图通过免翻地址（例如http://cl.XXX.site这种可直接访问的地址）进行下载，修改了代码中的main  url1   url2 中的网址参数 ,运行提示错误：Connect failed: HTTPConnectionPool(host='cl.a6u.site', port=80): Max retries exceeded with url: /thread0806.php?fid=16&search=&page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x02D3E5B0>: Failed
 to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
------
这个问题是什么原因？浏览器直接访问地址可以打开

**Comment by yikesoftware** [comment]
> 因为没有代理，意图通过免翻地址（例如[http://cl.XXX.site这种可直接访问的地址）进行下载，修改了代码中的main](http://cl.XXX.site%E8%BF%99%E7%A7%8D%E5%8F%AF%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AE%E7%9A%84%E5%9C%B0%E5%9D%80%EF%BC%89%E8%BF%9B%E8%A1%8C%E4%B8%8B%E8%BD%BD%EF%BC%8C%E4%BF%AE%E6%94%B9%E4%BA%86%E4%BB%A3%E7%A0%81%E4%B8%AD%E7%9A%84main) url1 url2 中的网址参数 ,运行提示错误：Connect failed: HTTPConnectionPool(host='cl.a6u.site', port=80): Max retries exceeded with url: /thread0806.php?fid=16&search=&page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x02D3E5B0>: Failed
> to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
> 这个问题是什么原因？浏览器直接访问地址可以打开

1、检查一下是否关闭了“使用代理"模式；2、镜像站的一些参数可能和主站不同，暂时没研究过，手头也没有

**Comment by weapon14** [comment]
1.已经修改默认为 useProxy=False
2.我又尝试了一下，免翻地址有时候使用的是https协议（https://cb.321i.xyz/index.php），有时候使用的是http协议（http://cl.a6u.site/index.php），这样的话使用的方法应该是不同的吧？主站使用的http

**Comment by yikesoftware** [comment]
这个影响倒不是很大


 
---原始邮件---
发件人: "weapon14"<notifications@github.com&gt;
发送时间: 2020年5月28日 16:34:51
收件人: "yikesoftware/t66y_spider"<t66y_spider@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"赤道企鹅"<1532494123@qq.com&gt;;
主题: Re: [yikesoftware/t66y_spider] 有的帖子下不全 (#1)




 
1.已经修改默认为 useProxy=False
 2.我又尝试了一下，免翻地址有时候使用的是https协议（https://cb.321i.xyz/index.php），有时候使用的是http协议（http://cl.a6u.site/index.php），这样的话使用的方法应该是不同的吧？主站使用的http

**Comment by weapon14** [comment]
那我再仔细研究一下代码吧！

**Comment by yikesoftware** [comment]
> 那我再仔细研究一下代码吧！

我刚才按照你的url试了下是没问题的，只要在启动命令那里加个-p 0，不用修改useProxy=False就可以了，我贴出来给你看
main_url="http://cl.a6u.site/"
url1="http://cl.a6u.site/thread0806.php?fid=8&search=&page="
url2="http://cl.a6u.site/thread0806.php?fid=16&search=&page="
然后启动参数是
python D:\se_pic\t66y_spider\Spider_of_t66y.py -s 1 -e 1 -m 300 -p 0

**Comment by weapon14** [comment]
在我本地环境依然无法运行。。。刚开始我怀疑是导入的包不对，pip list了一下，看到关键的几个包都有：bs4、requests、lxml、tqdm；再次运行的时候，运行界面提示：
{'http': 'socks5://localhost:1080', 'https': 'socks5://localhost:1080'}
path[',/t66y'] exists
Enjoy your life!
将下载【新時代的我們】和【達蓋爾的旗幟】的图片...
开始下载第 1 页
path['./t66y/新時代的我們'] exists
Connect failed: HTTPConnectionPool(host='cl.a6u.site', port=80): Max retries exceeded with url: /thread0806.php?fid=8&search=&page=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x038742E0>, 'Connec
tion to cl.a6u.site timed out. (connect timeout=20)'))
个人感觉依然是无法连接到服务器，比较奇怪，使用浏览器打开网址可以打开，比较奇怪了。

**Comment by yikesoftware** [comment]
启动命令是什么


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"weapon14"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 晚上8:18
收件人:&nbsp;"yikesoftware/t66y_spider"<t66y_spider@noreply.github.com&gt;;
抄送:&nbsp;"赤道企鹅"<1532494123@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yikesoftware/t66y_spider] 有的帖子下不全 (#1)





 
在我本地环境依然无法运行。。。刚开始我怀疑是导入的包不对，pip list了一下，看到关键的几个包都有：bs4、requests、lxml、tqdm；再次运行的时候，运行界面提示：
 {'http': 'socks5://localhost:1080', 'https': 'socks5://localhost:1080'}
 path[',/t66y'] exists
 Enjoy your life!
 将下载【新時代的我們】和【達蓋爾的旗幟】的图片...
 开始下载第 1 页
 path['./t66y/新時代的我們'] exists
 Connect failed: HTTPConnectionPool(host='cl.a6u.site', port=80): Max retries exceeded with url: /thread0806.php?fid=8&amp;search=&amp;page=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x038742E0&gt;, 'Connec
 tion to cl.a6u.site timed out. (connect timeout=20)'))
 个人感觉依然是无法连接到服务器，比较奇怪，使用浏览器打开网址可以打开，比较奇怪了。

**Comment by weapon14** [comment]
IDEA下环境下，直接 Spider_of_t66y.py -s 1 -e 1 -m 300 -p 0

**Comment by yikesoftware** [comment]
试试在powershell命令行环境下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"weapon14"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 晚上8:24
收件人:&nbsp;"yikesoftware/t66y_spider"<t66y_spider@noreply.github.com&gt;;
抄送:&nbsp;"赤道企鹅"<1532494123@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yikesoftware/t66y_spider] 有的帖子下不全 (#1)





 
IDEA下环境下，直接 Spider_of_t66y.py -s 1 -e 1 -m 300 -p 0

**Comment by weapon14** [comment]
powershell下无法运行  提示Filed to load './proxy' cause: [Errno 2] No such file or directory: 'proxy'；然后我又在IDEA运行时，发现又可以了！我最怕这种莫名其妙就能运行了的…

**Comment by yikesoftware** [comment]
因为目录不对....你要先切换到工作目录下，在目录下按住shift点击右键会有个在此处打开powershell，然后执行python xxxxxxx就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"weapon14"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 晚上8:36
收件人:&nbsp;"yikesoftware/t66y_spider"<t66y_spider@noreply.github.com&gt;;
抄送:&nbsp;"赤道企鹅"<1532494123@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yikesoftware/t66y_spider] 有的帖子下不全 (#1)





 
powershell下无法运行  提示Filed to load './proxy' cause: [Errno 2] No such file or directory: 'proxy'；然后我又在IDEA运行时，发现又可以了！我最怕这种莫名其妙就能运行了的…
